### ISSUE TITLE
Annotating D3 dataset with the CSO Classifier

### ISSUE THREAD

**Issue by angelosalatino** [jpwahle/lrec22-d3-dataset#1]
Hi,

I have downloaded your dataset, and extracted Computer Science topics from all the papers using the [CSO Classifier](https://github.com/angelosalatino/cso-classifier).

I have released this dataset at https://zenodo.org/record/7097148 in jsonl. I hope this can be helpful for your research.
I have also drafted a sort of document briefly explaining the extraction process: https://www.salatino.org/wp/wp-content/uploads/2022/09/Annotating-D3-dataset-with-the-CSO-Classifier.pdf

I hope this is useful for the whole community.
Best regards
Angelo

**Comment by jpwahle** [comment]
Hi Angelo 👋🏻
Thanks for the contribution, we appreciate it! I will take a closer look at the data and your repo and probably open a PR in the crawler and update our dataset with the November release.

**Comment by jpwahle** [comment]
Done. The new release 2.1 is available [here](https://huggingface.co/datasets/jpwahle/dblp-discovery-dataset) and [here](https://zenodo.org/record/7071698#.Y4DWnOzML0o)

**Comment by KorigamiK** [comment]
@angelosalatino hi, pretty late to the conversation but could you/did you ever share the code for annotating the existing d3 dataset?
